-- MySQL Script generated by MySQL Workbench
-- Sat Mar 16 13:10:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `nomePagador` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `valeRef` INT NULL,
  `valeAli` INT NULL,
  `salario` INT NOT NULL,
  PRIMARY KEY (`nomePagador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conta` (
  `nomePagador` VARCHAR(45) NOT NULL,
  `valorConta` DECIMAL(10,2) NOT NULL,
  `tipoConta` VARCHAR(45) NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `forma_pagamento` VARCHAR(45) NOT NULL,
  `Usuario_nomePagador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nomePagador`),
  INDEX `fk_Conta_Usuario_idx` (`Usuario_nomePagador` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_Usuario`
    FOREIGN KEY (`Usuario_nomePagador`)
    REFERENCES `mydb`.`Usuario` (`nomePagador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
